### ISSUE TITLE
Rename Repository + Project

### ISSUE THREAD

**Issue by sr229** [whats-this/owo.js#17]
IMHO, everyone seems to be following ``owo.<langExtension>``. We should work on a new name for the framework, starting from this repo.

Feel free to make suggestions

**Comment by aurieh** [comment]
But this is `owo.js`. We're good with standards.

**Comment by lordjbs** [comment]
how about OwOwOwOjs

**Comment by deansheather** [comment]
@lordjbs We don't appreciate non-constructive, stupid comments such as what you just said. I've deleted your comment.

**Comment by deansheather** [comment]
@devsnek Can you leave a reason for closing this issue instead of closing it without saying anything at all?

**Comment by devsnek** [comment]
issue was invalid
